In [1]:
#!/usr/bin/env python3
import torch
import numpy as np

In [12]:
encoder_model = torch.jit.load('srvs_10_100_test_2_10_best_encoder_model.pt')
encoder_model.to('cpu')
encoder_input = torch.tensor(np.array([[0.5, 0.6]]), dtype=torch.float32, requires_grad=True)
encoder_output = encoder_model(encoder_input)
print(encoder_output)
y = encoder_output
print(next(encoder_model.parameters()).dtype)

tensor([[ 0.3893, -0.8574]], grad_fn=<AddmmBackward0>)
torch.float32


In [13]:
encoder_input_derivative = torch.ones_like(y)
grad = torch.autograd.grad(outputs=y, inputs=encoder_input, grad_outputs=encoder_input_derivative, retain_graph=True)
print(grad)

(tensor([[-0.0797, -0.2586]]),)


In [14]:
jacobian = torch.autograd.functional.jacobian(encoder_model, encoder_input)
print(jacobian)

tensor([[[[-0.1177, -0.5546]],

         [[ 0.0380,  0.2960]]]])


In [15]:
y = encoder_output[0][0]
print(y)
encoder_input_derivative = torch.ones_like(y)
grad = torch.autograd.grad(outputs=y, inputs=encoder_input, grad_outputs=encoder_input_derivative, retain_graph=True, allow_unused=True)
print(grad)

tensor(0.3893, grad_fn=<SelectBackward0>)
(tensor([[-0.1177, -0.5546]]),)
